name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2      
      - name: apt helper action
        uses: ryankurte/action-apt@v0.2.0
        with:
          packages: wget ca-certificates curl gcc g++ perl python python-dev python-setuptools libgmp10 libgmp-dev locales bash make mawk file pkg-config git

      - name: Compile chapel run unit tests
        run: |
          export CHPL_VERSION=1.24.0
          export CHPL_HOME=/opt/chapel/$CHPL_VERSION
          export CHPL_GMP=system

          mkdir -p $CHPL_HOME
          curl -L https://github.com/chapel-lang/chapel/releases/download/$CHPL_VERSION/chapel-$CHPL_VERSION.tar.gz | tar -xzC /opt/chapel --transform 's/chapel-//'
          make -j 16 -C $CHPL_HOME
          make -j 16 -C $CHPL_HOME chpldoc test-venv mason
          
          export PATH=$PATH:$CHPL_HOME/bin/linux64-x86_64:$CHPL_HOME/util
          echo
          echo "------------ Compile Code -------------"
          echo          
          make -C ${GITHUB_WORKSPACE}
          echo
          echo "------------ Run Tests -------------"
          echo
          make test -C ${GITHUB_WORKSPACE}


