# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: apt helper action
        # You may pin to the exact commit or the version.
        # uses: ryankurte/action-apt@7356b2f8b9c6f8043a3d0ab3b991701dc817b759
        uses: ryankurte/action-apt@v0.2.0
        with:
          # apt packages to install
          packages: wget ca-certificates curl gcc g++ perl python python-dev python-setuptools libgmp10 libgmp-dev locales bash make mawk file pkg-config git

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
          echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
          dpkg-reconfigure --frontend=noninteractive locales && \
          update-locale LANG=en_US.UTF-8
