# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: apt helper action
        # You may pin to the exact commit or the version.
        # uses: ryankurte/action-apt@7356b2f8b9c6f8043a3d0ab3b991701dc817b759
        uses: ryankurte/action-apt@v0.2.0
        with:
          # apt packages to install
          packages: wget ca-certificates curl gcc g++ perl python python-dev python-setuptools libgmp10 libgmp-dev locales bash make mawk file pkg-config git

      - name: Compile chapel
        run: |
          export CHPL_VERSION=1.23.0
          export CHPL_HOME=/opt/chapel/$CHPL_VERSION
          export CHPL_GMP=system

          mkdir -p $CHPL_HOME
          curl -L https://github.com/chapel-lang/chapel/releases/download/$CHPL_VERSION/chapel-$CHPL_VERSION.tar.gz | tar -xzC /opt/chapel --transform 's/chapel-//'
          make -j 8 -C $CHPL_HOME
          make -j 8 -C $CHPL_HOME chpldoc test-venv mason
          
          export PATH=$PATH:$CHPL_HOME/bin/linux64-x86_64:$CHPL_HOME/util
          
          ls $CHPL_HOME/bin
      - name: Run Unit tests
        run: |
          make test -C ${GITHUB_WORKSPACE}


